var text = ["Kocham Cię.",
"Chce być z Tobą do końca świata.",
"Ożeń się ze mną kiedyś, proszę.",
"Powinniśmy wziąć ślub asap!!",
"Nie mogę się doczekać dnia gdy będę się koło Ciebie budził skarbie.",
"Mieć Ciebie, to więcej niż wygrana ",
"Chcę mięc z Toba kotki!!",
"Powinniśmy obejrzeć \"Gdzie jest nemo\" I całować się za każdym razem gdy zobaczymy rybe.",
"Twój głos jest dla mnie, jak deszcz dla roślin.",
"Dzien bez Ciebie to dzień stracony!",
"Ide spać myśląc o Tobie, to samo robie jak wstaje…",
"Czekam, gdy zamiast pisać Ci \"Dobranoc\", będę mógł Ci dać całusa na dobranoc ",
"Kiedy kolejny meet?",
"Nie moge się doczekać, aż opowiem naszym dzieciom historie jak się poznaliśmy.",
"Mam nadzieje, że nigdy nie będzie dnia w którym coś uniemożliwi mi napisanie Ci, jak bardzo Cię kocham",
"Jesteś śliczna.",
"Jesteś moim marzeniem, nie wiem jak nie dostrzegasz w sobie tego jakim jesteś arcydziełem.",
"Jeśli jesteś obok mnie, to znak, że jestem szczęśliwy.",
"Jestem tylko Twój <3",
"Jesteś przepiękna, na dodatek moja! Tylko moja..",
"Hej moja przyszła żono, jak leci?",
"Fakt, że jesteśmy w związku to moje życiowe osiągniecie.",
"Powiesz \"Tak\"?",
"Czym jest dzień w kielcach, bez Ciebie? Pfff",
"Słodka jesteś.",
"Jesteś taka słodka, że przez Ciebie nie słodze herbaty.",
"Słodziakkk, mój! Tylko mój!",
"Kocham Cię, wiesz?",
"Jak w przyszłości nie będę miał dużej willi wraz z Tobą w niej, to nie chce takiej przyszłości.",
"Hej, kiedy zaczniemy przygotowania do naszego ślubu",
"Hej, randka do urzędu, żeby potwierdzić związek małżeński?",
"Chce Cię już ustawić na tapete!!",
"Kocham Cię od naszego pierwszego spotkania!",
"Chciałbym Cię przytulić!!!",
"Wysyłam Ci całusa, łap go!",
"Zawsze zostawiam Ci miejsce w łóżku!",
"Co noc przytulam się do poduszki udając, że to Ty.",
"Dobranoc gdy nie dajesz mi całusa, to nie dobranoc…",
"Opiekuj sie dzieciorem!",
"Kocham jak wypominasz mi to, że jestem młodszy, emerytko!!",
"Najsłodsza kobieta jaką widziałem!",
"Powinnaś korzystać z talentu I zgłosić się do jakiegoś konkursu piękności! Każdy wie, że byś wygrała!",
"W naszej przyszłej willi powinniśmy zrobić pokój gamingowy, change my mind",
"Będę opowiadał naszym dzieciom naszą historie, jako dowód miłości",
"Nasze dzieci będą dumne z mamy jaką będą miały!",
"Moja Zuziaaa, tylko moja!!",
"Nie masz pojęcia jak cieszę sie, że jesteśmy razem kochanie.",
"Nie wiem, czy zdajesz sobie sprawe, ale nie nazywam Cie skarbem bez powodu. Jestes moim skarbem, skarbie",
"Kocham Cię bardzo mocno, pamietaj o tym!! Jestem Tylko Twój!",
"Mogłbym patrzeć na Ciebie godzinami.",
"Twoje oczy są takie piękne…",
"Jesteś taka kuci, kuci, kuci, kuci",
"Kiedy ślub???",
"Jesteś mojaaaa, tylko moja :3",
"Jeśli nie będziesz w mojej przyszłości, to nie chce takiej przyszłości.",
"Gdy słysze Twój głos to zawsze się uśmiecham!",
"Byłaś, jesteś I będziesz najlepszym wyborem",
"Czekam, na noce gdy razem będziemy mogli obejrzeć horror w jednym łóżku!",
"Z każda sekundą, gdy nie ma Cie obok, tęsknie coraz bardziej",
"Jesteś prześliczna!!!",
"Kiedy ustawiamy status związku na facebooku?",
"Hej, kocham Cie",
"Jesteś literalnie moim marzeniem",
"Jeśli teraz nie jesteś koło mnie, to wiedz, że tęsknie",
"Jesteś taka słodka, naprawdęęeę, sama słodycz.",
"Leżenie z Tobą to moje ulubione zajęcie",
"Kocham dawać Ci całusy",
"Kocham Cię przytulać!",
"Kocham gdy dajesz mi całusy",
"kocham gdy mnie przytulasz",
"Jesteś taka kochana!!!",
"Zależy mi na Tobie, miej o tym pojęcie!",
"Mój dzien staje się lepszy, przez zwykłą myśl o Tobie",
"Dużo dla mnie znaczysz, pamiętaj!!!",
"Jestem przy Tobie, zawsze!",
"W przyszłości będę Cię budził całusami",
"Chce z Tobą mieszkać, już!",
"Myślę, że powinnaś się do mnie przeteleportować, muszę Ci dać całusa!",
"Zależy mi na Tobie, zawsze i wszędzie!",
"Jeśli każdy chce byc przeciwko Tobie, to ja będę przeciwko każdemu",
"Nigdy nie myśl o sobie źle, jesteś śliczna, piękna, a w dodatku moja!",
"Nadal nie mogę uwierzyć, że mam taką ślicznotke jak Ty",
"Kocham Cię i spędzać z Tobą czas",
"Mam nadzeję, że wiesz jak dużo dla mnie znaczysz",
"Naturalnie piękna, moja Zuzia!!",
"Cieszę się, że nikt mi nie zgarnął Cię sprzed nosa", 
"Nie mów o sobie nigdy źle, bo to nie prawda!",
"Muszę Ci dać buziaka, bo zwariuje",
"Jeśli używasz tej strony w domu, to wiedz, że tęsknie",
"Ciesze się, że w tym wieku udało mi się znaleźć bratnią duszę!",
"Jesteś taka słodka, z chęcią bym Cię zjadł",
"Chcę tylko Ciebieee, ślicznotko!!",
"Czasami żałuje, że nie mogę przedstawić mojego uczucia do Ciebie, jest po prostu za wielkie by opisać je słowami",
"Przytulas?",
"Nie moge przestać o Tobie myśleć!",
"Kocham tiktoki od Ciebie",
"Nigdy się nie narzucasz, zawsze poprawiasz mi humor!",
"Aż trudno opisać moją chęć przytulenia Cię"]

function onHeartClicked() {
    document.getElementById("heart").style.opacity = "1";
    document.getElementById("heart").style.top = "50%";
    document.getElementById("heart").style.transform = "scale(1.3)";
    setTimeout(function () { 
        document.getElementById("title").style.display = "none";
        document.getElementById("textbutton").style.display = "block";
        document.getElementById("textbutton").innerHTML = "Losuj Kolejny Tekst!"
        
        document.getElementById("description").innerText = text[(Math.floor(Math.random() * text.length))] + " ~ Twój Paweł :3"
        document.getElementById("heart").style.top = "125%";
        document.getElementById("heart").style.opacity = "0";
        document.getElementById("heart").style.transform = "scale(1.0)";
    }, 2500)
    
}
